// ------------------------------------------------------------------------------
// <auto-generated>
//     This file was generated by Extensibility Tools v1.10.211
// </auto-generated>
// ------------------------------------------------------------------------------
namespace SharperCryptoApiAnalysis.Vsix
{
    using System;
    
    /// <summary>
    /// Helper class that exposes all GUIDs used across VS Package.
    /// </summary>
    internal sealed partial class PackageGuids
    {
        public const string SharperCryptoApiAnalysisPackageString = "7bd4f491-d3dd-4b98-9f02-66b65dee88bf";
        public const string SharperCryptoApiAnalysisCommandSetString = "218ff211-c215-4600-b42e-b7568e1c4171";
        public const string ToolbarCommandSetString = "3b6e23f0-2f47-4f93-be76-dcaad30a6aaf";
        public static Guid SharperCryptoApiAnalysisPackage = new Guid(SharperCryptoApiAnalysisPackageString);
        public static Guid SharperCryptoApiAnalysisCommandSet = new Guid(SharperCryptoApiAnalysisCommandSetString);
        public static Guid ToolbarCommandSet = new Guid(ToolbarCommandSetString);
    }
    /// <summary>
    /// Helper class that encapsulates all CommandIDs uses across VS Package.
    /// </summary>
    internal sealed partial class PackageIds
    {
        public const int SharperAnalysisMenu = 0x0001;
        public const int HelpMenu = 0x0003;
        public const int MyMenuGroup = 0x1001;
        public const int HelpMenuGroup = 0x1002;
        public const int AboutCommand = 0x2001;
        public const int ShowPaneCommand = 0x2002;
        public const int AddCryptoAbstractionFile = 0x2003;
        public const int ToolbarNavigationMenuGroup = 0x1110;
        public const int SharperCryptoApiAnalysisToolbar = 0x1120;
        public const int ToolbarManageConnectionsId = 0x1150;
        public const int ToolbarManageExtensionsId = 0x1160;
        public const int ToolbarAnalyzerDetailId = 0x1170;
        public const int ToolbarAnalyzerReportsId = 0x1180;
    }
}
